name: Backup Directory & Push to Artifacts

on:
  schedule:
    - cron: "0 0 * * *" # Every Day at Midnight

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: Backup MySQL DB
      uses: valerianpereira/backup-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        type: db
        db_type: mysql
        db_user: ${{ secrets.MYSQL_USER }}
        db_pass: ${{ secrets.MYSQL_PASS }}
        db_port: 3306
        db_name: world

    # This is just an example use case, not tested.
    - name: Push Backups to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mysql-backups
        path: /github/workspace/backups/
